# Generated by Django 5.2.10 on 2026-04-08 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('confirmed_received', 'Confirmed Received'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
