# Generated by Django 6.0.3 on 2026-03-16 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_listing_reject_reason_userprofile_warning_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreport',
            name='admin_reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
