# Generated by Django 6.0.3 on 2026-03-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_listingimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminauditlog',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='adminauditlog',
            name='object_id',
        ),
        migrations.AddField(
            model_name='adminauditlog',
            name='target_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adminauditlog',
            name='target_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
