# Generated by Django 6.0.3 on 2026-03-23 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_userprofile_block_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreport',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Chờ xử lý'), ('RESOLVED', 'Đã xử lý (Vi phạm)'), ('REJECTED', 'Đã xử lý (Bỏ qua)')], default='OPEN', max_length=20),
        ),
    ]
