# Generated by Django 4.2.29 on 2026-04-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_alter_userreport_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreport',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Chờ xử lý'), ('RESOLVED', 'Đã xử lý (Vi phạm)'), ('REJECTED', 'Đã xử lý (Bỏ qua)')], default='PENDING', max_length=20),
        ),
    ]
